export const MAX_ALLOWED_CALLBACK_DATA = 64;
export const TG_CLASS_PATH_METADATA = 'TG_CLASS_PATH_METADATA';
export const TG_FUNCTION_PATH_METADATA = 'TG_FUNCTION_PATH_METADATA';
export const TG_REQUEST_METHOD = 'TG_REQUEST_METHOD';
